# -*- coding: utf-8 -*-
"""accent_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XARaG8R_KD-LACyLMuniNggiuISQPNnE
"""

import os
import tempfile
import yt_dlp
import whisper
from langdetect import detect

import os
import tempfile
import yt_dlp
import ffmpeg

def download_audio_youtube(url):
    tmp_video = tempfile.NamedTemporaryFile(suffix=".mp4", delete=False)
    tmp_audio = tempfile.NamedTemporaryFile(suffix=".wav", delete=False)

    video_path = tmp_video.name
    audio_path = tmp_audio.name

    # Step 1: Download video (just best format)
    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': video_path,
        'quiet': True,
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])

    # Step 2: Convert to WAV using ffmpeg
    try:
        ffmpeg.input(video_path).output(audio_path, format='wav').run(quiet=True, overwrite_output=True)
    except Exception as e:
        raise RuntimeError("ffmpeg conversion failed") from e

    # Optional: Remove video after conversion
    os.remove(video_path)

    return audio_path


def estimate_accent(text):
    text = text.lower()
    american = ["gonna", "wanna", "gotta", "dude", "awesome", "bro", "kinda", "y’all"]
    british = ["shall", "cheers", "mate", "bloody", "brilliant", "rubbish", "fancy", "flat"]
    australian = ["g'day", "mate", "no worries", "arvo", "reckon", "heaps", "how ya going"]

    am = sum(word in text for word in american)
    br = sum(word in text for word in british)
    au = sum(word in text for word in australian)

    if au > max(am, br): return "Australian", 85
    elif am > max(br, au): return "American", 80
    elif br > max(am, au): return "British", 75
    else: return "Uncertain English", 60

def run_accent_detection(video_url):
    audio_path = download_audio_youtube(video_url)
    model = whisper.load_model("base")
    result = model.transcribe(audio_path)
    transcript = result["text"]
    lang = detect(transcript)
    os.remove(audio_path)

    if lang != 'en':
        return None

    accent, confidence = estimate_accent(transcript)
    return accent, confidence, transcript
